apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-staging-2
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-staging-2
  template:
    metadata:
      labels:
        app: guestbook-ui-staging-2
        eti: dffdkkffff

    spec:
      containers:
        - image: quay.io/argoprojlabs/argocd-e2e-container:0.1
          name: guestbook-ui-staging-2-test
          ports:
            - containerPort: 80
